<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        // CCS 101-112 courses
        $courses = [
            [
                'course_code' => 'CCS 101',
                'course_name' => 'Introduction to Computer Science',
                'description' => 'Fundamental concepts of computer science and programming',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Dr. John Smith',
                'schedule' => 'MWF 9:00-10:30 AM',
                'room' => 'Room 101',
                'max_students' => 40,
                'current_students' => 35,
                'status' => 'active',
                'prerequisites' => [],
                'year_level' => '1st',
            ],
            [
                'course_code' => 'CCS 102',
                'course_name' => 'Programming Fundamentals',
                'description' => 'Introduction to programming concepts and problem solving',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Prof. Jane Doe',
                'schedule' => 'TTH 1:00-2:30 PM',
                'room' => 'Room 102',
                'max_students' => 35,
                'current_students' => 32,
                'status' => 'active',
                'prerequisites' => ['CCS 101'],
                'year_level' => '1st',
            ],
            [
                'course_code' => 'CCS 103',
                'course_name' => 'Data Structures and Algorithms',
                'description' => 'Advanced data structures and algorithm analysis',
                'credits' => 4,
                'department' => 'Computer Science',
                'semester' => 'Second Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Dr. Robert Johnson',
                'schedule' => 'MWF 2:00-3:30 PM',
                'room' => 'Room 103',
                'max_students' => 30,
                'current_students' => 28,
                'status' => 'active',
                'prerequisites' => ['CCS 102'],
                'year_level' => '2nd',
            ],
            [
                'course_code' => 'CCS 104',
                'course_name' => 'Web Development Fundamentals',
                'description' => 'Introduction to web development with HTML, CSS, and JavaScript',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Prof. Emily Davis',
                'schedule' => 'TTH 9:00-10:30 AM',
                'room' => 'Room 104',
                'max_students' => 35,
                'current_students' => 30,
                'status' => 'active',
                'prerequisites' => ['CCS 103'],
                'year_level' => '2nd',
            ],
            [
                'course_code' => 'CCS 105',
                'course_name' => 'Database Management Systems',
                'description' => 'Database design, implementation, and management',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'Second Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Dr. Michael Wilson',
                'schedule' => 'MWF 1:00-2:30 PM',
                'room' => 'Room 105',
                'max_students' => 30,
                'current_students' => 27,
                'status' => 'active',
                'prerequisites' => ['CCS 104'],
                'year_level' => '2nd',
            ],
            [
                'course_code' => 'CCS 106',
                'course_name' => 'Software Engineering',
                'description' => 'Software development methodologies and project management',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Prof. Sarah Brown',
                'schedule' => 'TTH 2:00-3:30 PM',
                'room' => 'Room 106',
                'max_students' => 25,
                'current_students' => 23,
                'status' => 'active',
                'prerequisites' => ['CCS 105'],
                'year_level' => '3rd',
            ],
            [
                'course_code' => 'CCS 107',
                'course_name' => 'Computer Networks',
                'description' => 'Computer network fundamentals and protocols',
                'credits' => 4,
                'department' => 'Computer Science',
                'semester' => 'Second Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Dr. David Martinez',
                'schedule' => 'MWF 10:00-11:30 AM',
                'room' => 'Room 107',
                'max_students' => 30,
                'current_students' => 26,
                'status' => 'active',
                'prerequisites' => ['CCS 106'],
                'year_level' => '3rd',
            ],
            [
                'course_code' => 'CCS 108',
                'course_name' => 'Operating Systems',
                'description' => 'Operating system concepts and implementation',
                'credits' => 4,
                'department' => 'Computer Science',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Prof. Lisa Anderson',
                'schedule' => 'TTH 10:00-11:30 AM',
                'room' => 'Room 108',
                'max_students' => 25,
                'current_students' => 22,
                'status' => 'active',
                'prerequisites' => ['CCS 107'],
                'year_level' => '3rd',
            ],
            [
                'course_code' => 'CCS 109',
                'course_name' => 'Artificial Intelligence',
                'description' => 'Introduction to artificial intelligence concepts and applications',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'Second Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Dr. James Taylor',
                'schedule' => 'MWF 3:00-4:30 PM',
                'room' => 'Room 109',
                'max_students' => 20,
                'current_students' => 18,
                'status' => 'active',
                'prerequisites' => ['CCS 108'],
                'year_level' => '4th',
            ],
            [
                'course_code' => 'CCS 110',
                'course_name' => 'Machine Learning',
                'description' => 'Machine learning algorithms and applications',
                'credits' => 4,
                'department' => 'Computer Science',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Prof. Jennifer White',
                'schedule' => 'TTH 3:00-4:30 PM',
                'room' => 'Room 110',
                'max_students' => 20,
                'current_students' => 19,
                'status' => 'inactive',
                'prerequisites' => ['CCS 109'],
                'year_level' => '4th',
            ],
            [
                'course_code' => 'CCS 111',
                'course_name' => 'Cybersecurity Fundamentals',
                'description' => 'Introduction to cybersecurity principles and practices',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'Second Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Dr. William Harris',
                'schedule' => 'MWF 11:00-12:30 PM',
                'room' => 'Room 111',
                'max_students' => 25,
                'current_students' => 15,
                'status' => 'inactive',
                'prerequisites' => ['CCS 110'],
                'year_level' => '4th',
            ],
            [
                'course_code' => 'CCS 112',
                'course_name' => 'Mobile Application Development',
                'description' => 'Mobile app development for iOS and Android platforms',
                'credits' => 3,
                'department' => 'Computer Science',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'instructor' => 'Prof. Maria Garcia',
                'schedule' => 'TTH 11:00-12:30 PM',
                'room' => 'Room 112',
                'max_students' => 20,
                'current_students' => 12,
                'status' => 'inactive',
                'prerequisites' => ['CCS 111'],
                'year_level' => '4th',
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
