<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Professor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ProfessorSeeder extends Seeder
{
    public function run(): void
    {
        $professors = [
            [
                'first_name' => 'Juan',
                'middle_name' => 'Santos',
                'last_name' => 'Dela Cruz',
                'email' => 'juan.professor@ccs.edu',
                'age' => 35,
                'birthday' => '1989-05-15',
                'blood_type' => 'O+',
                'gender' => 'Male',
                'contact_number' => '+639123456789',
                'address' => '123 Street, City',
                'educational_attainment' => 'Master of Science in Computer Science',
                'experience' => '10 years in teaching and industry',
                'courses_handled' => 'Data Structures, Algorithm Analysis, Web Development',
                'role' => 'Associate Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Computer Science Society',
                'application_date' => '2020-06-01',
            ],
            [
                'first_name' => 'Maria',
                'middle_name' => 'Garcia',
                'last_name' => 'Santos',
                'email' => 'maria.santos@ccs.edu',
                'age' => 42,
                'birthday' => '1982-03-22',
                'blood_type' => 'A+',
                'gender' => 'Female',
                'contact_number' => '+639234567890',
                'address' => '456 Avenue, Town',
                'educational_attainment' => 'PhD in Information Technology',
                'experience' => '15 years in academia and research',
                'courses_handled' => 'Database Systems, Software Engineering, AI',
                'role' => 'Full Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'IT Research Association',
                'application_date' => '2018-08-15',
            ],
            [
                'first_name' => 'Roberto',
                'middle_name' => 'Reyes',
                'last_name' => 'Lim',
                'email' => 'roberto.lim@ccs.edu',
                'age' => 38,
                'birthday' => '1986-07-10',
                'blood_type' => 'B+',
                'gender' => 'Male',
                'contact_number' => '+639345678901',
                'address' => '789 Boulevard, District',
                'educational_attainment' => 'Master of Science in Computer Science',
                'experience' => '12 years in software development',
                'courses_handled' => 'Web Development, Mobile Apps, Cloud Computing',
                'role' => 'Assistant Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Web Developers Guild',
                'application_date' => '2019-02-20',
            ],
            [
                'first_name' => 'Elena',
                'middle_name' => 'Mendoza',
                'last_name' => 'Castillo',
                'email' => 'elena.castillo@ccs.edu',
                'age' => 45,
                'birthday' => '1979-11-30',
                'blood_type' => 'AB+',
                'gender' => 'Female',
                'contact_number' => '+639456789012',
                'address' => '321 Highway, Province',
                'educational_attainment' => 'PhD in Computer Science',
                'experience' => '18 years in research and teaching',
                'courses_handled' => 'Machine Learning, Data Mining, Statistics',
                'role' => 'Full Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Data Science Society',
                'application_date' => '2017-01-10',
            ],
            [
                'first_name' => 'Carlos',
                'middle_name' => 'Tan',
                'last_name' => 'Wong',
                'email' => 'carlos.wong@ccs.edu',
                'age' => 33,
                'birthday' => '1991-09-18',
                'blood_type' => 'O-',
                'gender' => 'Male',
                'contact_number' => '+639567890123',
                'address' => '654 Lane, County',
                'educational_attainment' => 'Master of Science in Information Technology',
                'experience' => '8 years in network security',
                'courses_handled' => 'Cybersecurity, Network Administration, Cryptography',
                'role' => 'Assistant Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Security Professionals Network',
                'application_date' => '2021-03-25',
            ],
            [
                'first_name' => 'Patricia',
                'middle_name' => 'Lee',
                'last_name' => 'Kim',
                'email' => 'patricia.kim@ccs.edu',
                'age' => 40,
                'birthday' => '1984-12-05',
                'blood_type' => 'A-',
                'gender' => 'Female',
                'contact_number' => '+639678901234',
                'address' => '987 Road, Region',
                'educational_attainment' => 'PhD in Computer Engineering',
                'experience' => '14 years in hardware and software',
                'courses_handled' => 'Computer Architecture, Embedded Systems, IoT',
                'role' => 'Associate Professor',
                'employment_type' => 'Full-time',
                'department' => 'Engineering',
                'organization' => 'Engineering Research Council',
                'application_date' => '2018-11-12',
            ],
            [
                'first_name' => 'Antonio',
                'middle_name' => 'David',
                'last_name' => 'Miller',
                'email' => 'antonio.miller@ccs.edu',
                'age' => 36,
                'birthday' => '1988-04-25',
                'blood_type' => 'B-',
                'gender' => 'Male',
                'contact_number' => '+639789012345',
                'address' => '147 Street, Metro',
                'educational_attainment' => 'Master of Science in Software Engineering',
                'experience' => '11 years in agile development',
                'courses_handled' => 'Agile Methodologies, DevOps, Software Testing',
                'role' => 'Assistant Professor',
                'employment_type' => 'Part-time',
                'department' => 'CCS',
                'organization' => 'Agile Alliance',
                'application_date' => '2020-09-08',
            ],
            [
                'first_name' => 'Sophia',
                'middle_name' => 'Johnson',
                'last_name' => 'Taylor',
                'email' => 'sophia.taylor@ccs.edu',
                'age' => 39,
                'birthday' => '1985-08-14',
                'blood_type' => 'O+',
                'gender' => 'Female',
                'contact_number' => '+639890123456',
                'address' => '258 Avenue, Capital',
                'educational_attainment' => 'PhD in Data Science',
                'experience' => '13 years in data analytics',
                'courses_handled' => 'Big Data Analytics, Business Intelligence, Python',
                'role' => 'Associate Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Data Analytics Association',
                'application_date' => '2019-07-22',
            ],
            [
                'first_name' => 'Francisco',
                'middle_name' => 'Martinez',
                'last_name' => 'Brown',
                'email' => 'francisco.brown@ccs.edu',
                'age' => 41,
                'birthday' => '1983-01-30',
                'blood_type' => 'A+',
                'gender' => 'Male',
                'contact_number' => '+639901234567',
                'address' => '369 Boulevard, State',
                'educational_attainment' => 'Master of Science in Computer Engineering',
                'experience' => '16 years in systems architecture',
                'courses_handled' => 'Systems Design, Enterprise Architecture, Cloud Solutions',
                'role' => 'Full Professor',
                'employment_type' => 'Full-time',
                'department' => 'Engineering',
                'organization' => 'Systems Engineering Society',
                'application_date' => '2017-05-18',
            ],
            [
                'first_name' => 'Isabella',
                'middle_name' => 'Wilson',
                'last_name' => 'Davis',
                'email' => 'isabella.davis@ccs.edu',
                'age' => 34,
                'birthday' => '1990-06-12',
                'blood_type' => 'B+',
                'gender' => 'Female',
                'contact_number' => '+639012345678',
                'address' => '741 Highway, District',
                'educational_attainment' => 'Master of Science in Artificial Intelligence',
                'experience' => '9 years in AI research',
                'courses_handled' => 'Natural Language Processing, Computer Vision, Deep Learning',
                'role' => 'Assistant Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'AI Research Group',
                'application_date' => '2021-01-15',
            ],
            [
                'first_name' => 'Miguel',
                'middle_name' => 'Anderson',
                'last_name' => 'Thomas',
                'email' => 'miguel.thomas@ccs.edu',
                'age' => 37,
                'birthday' => '1987-10-28',
                'blood_type' => 'AB-',
                'gender' => 'Male',
                'contact_number' => '+639123456789',
                'address' => '852 Lane, County',
                'educational_attainment' => 'PhD in Computer Science',
                'experience' => '12 years in theoretical computer science',
                'courses_handled' => 'Theory of Computation, Algorithms, Discrete Mathematics',
                'role' => 'Associate Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Theoretical Computer Science Society',
                'application_date' => '2019-04-30',
            ],
            [
                'first_name' => 'Gabriela',
                'middle_name' => 'Jackson',
                'last_name' => 'White',
                'email' => 'gabriela.white@ccs.edu',
                'age' => 43,
                'birthday' => '1981-02-17',
                'blood_type' => 'O-',
                'gender' => 'Female',
                'contact_number' => '+639234567890',
                'address' => '963 Road, Region',
                'educational_attainment' => 'Master of Science in Information Systems',
                'experience' => '17 years in IT management',
                'courses_handled' => 'IT Project Management, Systems Analysis, Business Process',
                'role' => 'Full Professor',
                'employment_type' => 'Full-time',
                'department' => 'Business',
                'organization' => 'IT Management Association',
                'application_date' => '2016-12-03',
            ],
            [
                'first_name' => 'Ricardo',
                'middle_name' => 'Harris',
                'last_name' => 'Martin',
                'email' => 'ricardo.martin@ccs.edu',
                'age' => 32,
                'birthday' => '1992-05-08',
                'blood_type' => 'A-',
                'gender' => 'Male',
                'contact_number' => '+639345678901',
                'address' => '147 Street, Metro',
                'educational_attainment' => 'Master of Science in Game Development',
                'experience' => '7 years in game design and development',
                'courses_handled' => 'Game Design, Unity Development, Computer Graphics',
                'role' => 'Assistant Professor',
                'employment_type' => 'Part-time',
                'department' => 'CCS',
                'organization' => 'Game Developers Association',
                'application_date' => '2022-06-14',
            ],
            [
                'first_name' => 'Daniela',
                'middle_name' => 'Thompson',
                'last_name' => 'Garcia',
                'email' => 'daniela.garcia@ccs.edu',
                'age' => 46,
                'birthday' => '1978-09-22',
                'blood_type' => 'B-',
                'gender' => 'Female',
                'contact_number' => '+639456789012',
                'address' => '258 Avenue, Capital',
                'educational_attainment' => 'PhD in Human-Computer Interaction',
                'experience' => '19 years in UX research and design',
                'courses_handled' => 'User Experience Design, Interface Design, Usability Testing',
                'role' => 'Full Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'UX Professionals Network',
                'application_date' => '2015-08-27',
            ],
            [
                'first_name' => 'Luis',
                'middle_name' => 'Robinson',
                'last_name' => 'Clark',
                'email' => 'luis.clark@ccs.edu',
                'age' => 35,
                'birthday' => '1989-12-03',
                'blood_type' => 'AB+',
                'gender' => 'Male',
                'contact_number' => '+639567890123',
                'address' => '369 Boulevard, State',
                'educational_attainment' => 'Master of Science in Blockchain Technology',
                'experience' => '10 years in cryptocurrency and blockchain',
                'courses_handled' => 'Blockchain Fundamentals, Cryptocurrency, Smart Contracts',
                'role' => 'Assistant Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Blockchain Innovation Hub',
                'application_date' => '2020-10-19',
            ],
            [
                'first_name' => 'Valentina',
                'middle_name' => 'Rodriguez',
                'last_name' => 'Lewis',
                'email' => 'valentina.lewis@ccs.edu',
                'age' => 38,
                'birthday' => '1986-07-15',
                'blood_type' => 'O+',
                'gender' => 'Female',
                'contact_number' => '+639678901234',
                'address' => '741 Highway, District',
                'educational_attainment' => 'PhD in Quantum Computing',
                'experience' => '12 years in quantum research',
                'courses_handled' => 'Quantum Computing, Quantum Algorithms, Quantum Information',
                'role' => 'Associate Professor',
                'employment_type' => 'Full-time',
                'department' => 'Physics',
                'organization' => 'Quantum Computing Society',
                'application_date' => '2018-03-11',
            ],
            [
                'first_name' => 'Andres',
                'middle_name' => 'Walker',
                'last_name' => 'Hall',
                'email' => 'andres.hall@ccs.edu',
                'age' => 40,
                'birthday' => '1984-04-09',
                'blood_type' => 'A+',
                'gender' => 'Male',
                'contact_number' => '+639789012345',
                'address' => '852 Lane, County',
                'educational_attainment' => 'Master of Science in Cybersecurity',
                'experience' => '14 years in ethical hacking',
                'courses_handled' => 'Ethical Hacking, Penetration Testing, Security Auditing',
                'role' => 'Associate Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Cybersecurity Alliance',
                'application_date' => '2019-01-28',
            ],
            [
                'first_name' => 'Camila',
                'middle_name' => 'Allen',
                'last_name' => 'Young',
                'email' => 'camila.young@ccs.edu',
                'age' => 33,
                'birthday' => '1991-11-25',
                'blood_type' => 'B+',
                'gender' => 'Female',
                'contact_number' => '+639890123456',
                'address' => '963 Road, Region',
                'educational_attainment' => 'Master of Science in Cloud Computing',
                'experience' => '8 years in cloud architecture',
                'courses_handled' => 'Cloud Architecture, AWS, Azure, DevOps',
                'role' => 'Assistant Professor',
                'employment_type' => 'Part-time',
                'department' => 'CCS',
                'organization' => 'Cloud Computing Association',
                'application_date' => '2021-05-06',
            ],
            [
                'first_name' => 'Diego',
                'middle_name' => 'King',
                'last_name' => 'Wright',
                'email' => 'diego.wright@ccs.edu',
                'age' => 44,
                'birthday' => '1980-01-18',
                'blood_type' => 'AB-',
                'gender' => 'Male',
                'contact_number' => '+639901234567',
                'address' => '147 Street, Metro',
                'educational_attainment' => 'PhD in Software Engineering',
                'experience' => '18 years in software architecture',
                'courses_handled' => 'Software Architecture, Design Patterns, Code Quality',
                'role' => 'Full Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Software Engineering Institute',
                'application_date' => '2016-09-14',
            ],
            [
                'first_name' => 'Luciana',
                'middle_name' => 'Scott',
                'last_name' => 'Green',
                'email' => 'luciana.green@ccs.edu',
                'age' => 36,
                'birthday' => '1988-06-30',
                'blood_type' => 'O-',
                'gender' => 'Female',
                'contact_number' => '+639012345678',
                'address' => '258 Avenue, Capital',
                'educational_attainment' => 'Master of Science in Data Engineering',
                'experience' => '11 years in big data systems',
                'courses_handled' => 'Data Engineering, ETL Processes, Data Warehousing',
                'role' => 'Assistant Professor',
                'employment_type' => 'Full-time',
                'department' => 'CCS',
                'organization' => 'Data Engineering Society',
                'application_date' => '2020-02-22',
            ]
        ];

        foreach ($professors as $professorData) {
            $user = User::create([
                'name' => $professorData['first_name'] . ' ' . $professorData['last_name'],
                'email' => $professorData['email'],
                'password' => Hash::make('password'),
                'role' => 'professor',
            ]);

            Professor::create([
                'professor_unique_id' => 'PROF-' . strtoupper(Str::random(8)),
                'user_id' => $user->id,
                'first_name' => $professorData['first_name'],
                'middle_name' => $professorData['middle_name'],
                'last_name' => $professorData['last_name'],
                'age' => $professorData['age'],
                'birthday' => $professorData['birthday'],
                'blood_type' => $professorData['blood_type'],
                'disability_status' => false,
                'gender' => $professorData['gender'],
                'email' => $professorData['email'],
                'contact_number' => $professorData['contact_number'],
                'address' => $professorData['address'],
                'educational_attainment' => $professorData['educational_attainment'],
                'experience' => $professorData['experience'],
                'courses_handled' => $professorData['courses_handled'],
                'role' => $professorData['role'],
                'employment_type' => $professorData['employment_type'],
                'department' => $professorData['department'],
                'organization' => $professorData['organization'],
                'application_date' => $professorData['application_date'],
            ]);

            $this->command->info("Professor user created: {$professorData['email']} / password");
        }
    }
}
